// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "LandscapeProxy.h"
#include "GameFramework/Actor.h"
#include "LFLandscapeGrassHack.generated.h"

UCLASS()
class LIDARFOREST_API ALFLandscapeGrassHack : public AActor
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	ALFLandscapeGrassHack();

	UPROPERTY()
	USceneComponent* Root;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	ALandscapeProxy* Landscape;

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	void UpdateGrass(ALandscapeProxy* LandscapeToUpdate);

};
